name: pyhelios_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - gdal
  - polyscope
  - matplotlib
  - geopandas
  - numpy
  - xmlschema
  - pip:
    - open3d
    - laspy
