model_config:
  target: src.models.lrm.InstantNeRF
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 80
    rendering_samples_per_ray: 128


infer_config:
  unet_path: ckpts/zero123plus.ckpt
  model_path: ckpts/lrm.ckpt
  mesh_threshold: 10.0
  mesh_resolution: 512
  render_resolution: 512